CREATE TABLE sir_master(
                  StudyID INTEGER,
				  PatientID  INTEGER,				  
				  VtfHuvudId INTEGER,
				  Unit  TEXT,
				  AdmissionYear  INTEGER,
				  Age  INTEGER,
				  SexMale INTEGER,
				  CareType TEXT,
				  MotherClinic  TEXT,
				  EmergencyAdmission INTEGER,
				  UnderwentSurgery TEXT,
				  AdmittedFrom TEXT,
				  AdmissionReason TEXT,
				  AdmissionDateTime REAL,
				  DischargedTo TEXT,
				  DischargeReason TEXT,
				  DischargeDateTime REAL,
				  CareTimeMinutes INTEGER,
				  Outcome TEXT,
				  DeathDateTime REAL,
				  PrimaryICUICD TEXT,
				  TreatmentStrategy TEXT,
				  VTS INTEGER,
				  VTS2014 INTEGER,
				  PRIMARY KEY (StudyID, VtfHuvudId, AdmissionDateTime)
                  FOREIGN KEY (StudyID) REFERENCES subjects(StudyID) ON UPDATE CASCADE ON DELETE SET NULL,
				  FOREIGN KEY (PatientID) REFERENCES patients(PatientID) ON UPDATE CASCADE ON DELETE SET NULL
                  ) WITHOUT ROWID;