CREATE TABLE sir_saps(
                  VtfHuvudId INTEGER PRIMARY KEY,
				  Points REAL,
				  EMR REAL,
				  CancerTherapy INTEGER,
				  ChronicHeartFailure INTEGER,
				  HematologicMalignancy INTEGER,
				  Cirrhosis INTEGER,
				  AIDS INTEGER,
				  Cancer INTEGER,
				  DaysInHospital INTEGER,
				  VasoactiveTherapy INTEGER,
				  TypeOfSurgery TEXT,
				  NosocomoialInfection INTEGER,
				  DeepAirwayInfection INTEGER,
				  GCS INTEGER,
				  GCSEye INTEGER,
				  GCSVerbal INTEGER,
				  RLS85 INTEGER,
				  BilirubinMax REAL,
				  TemperatureMax REAL,
				  CreatinineMax REAL,
				  LeukocytesMax REAL,
				  ThrombocytesMin REAL,
				  SystolicBloodPressureMin REAL,
				  MechanicalVentilation INTEGER,
				  FiO2 REAL,
				  PaO2 REAL,
				  OnlyObservation INTEGER,
				  Cardiovascular TEXT,
				  Hepatic TEXT,
				  Gastrointestinal TEXT,
				  Neurologic TEXT,
				  Renal TEXT,
				  Respiratory TEXT,
				  Hematologic TEXT,
				  Metabolic TEXT,
				  Trauma INTEGER,
				  OtherReason INTEGER,  
				  FOREIGN KEY (VtfHuvudId) REFERENCES sir_master(VtfHuvudId) ON UPDATE CASCADE ON DELETE SET NULL
                  ) WITHOUT ROWID;