CREATE TABLE pharma_compounds(
CompID INTEGER PRIMARY KEY NOT NULL,
CompName TEXT) WITHOUT ROWID;

CREATE TABLE pharma_names(
PharmaID INTEGER PRIMARY KEY NOT NULL, 
PharmaName TEXT,
Unit TEXT,
PharmaType INTEGER) WITHOUT ROWID;

CREATE TABLE pharma_orders(
OrderNumber INTEGER PRIMARY KEY NOT NULL,
PatientID INTEGER NOT NULL,
FOREIGN KEY (PatientID) REFERENCES patients(PatientID) ON UPDATE CASCADE ON DELETE SET NULL
) WITHOUT ROWID;

CREATE TABLE pharma_prep(
OrderNumber INTEGER NOT NULL, 
PharmaID INTEGER NOT NULL, 
CompID INTEGER NOT NULL, 
Concentration REAL NOT NULL, 
Unit TEXT NOT NULL, 
N_obs INTEGER NOT NULL,
PRIMARY KEY (OrderNumber, CompID, PharmaID),
FOREIGN KEY (OrderNumber) REFERENCES pharma_orders(OrderNumber) ON UPDATE CASCADE ON DELETE SET NULL,
FOREIGN KEY (PharmaID) REFERENCES pharma_names(PharmaID) ON UPDATE CASCADE ON DELETE SET NULL,
FOREIGN KEY (CompID) REFERENCES pharma_compounds(CompID) ON UPDATE CASCADE ON DELETE SET NULL
) WITHOUT ROWID;

CREATE TABLE pharma_tmp(
	PatientID INTEGER, 
	OrderNumber INTEGER, 
	CompID INTEGER, 
	PharmaID INTEGER, 
	DateTime REAL, 
	GivenDose REAL
);

CREATE TABLE pharma_infusions_tmp(
	OrderNumber INTEGER NOT NULL, 
	DateTime REAL, 
	Rate REAL,
	FOREIGN KEY (OrderNumber) REFERENCES pharma_orders(OrderNumber) ON UPDATE CASCADE ON DELETE SET NULL
);

/*
CREATE TABLE pharma(
	OrderNumber INTEGER, 
	CompID INTEGER, 
	PharmaID INTEGER, 
	DateTime REAL, 
	RowNumber INTEGER,
	GivenDose REAL
	PRIMARY KEY (OrderNumber, CompID, PharmaID, DateTime, RowNumber),
	FOREIGN KEY (PatientID) REFERENCES patients(PatientID) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (PharmaID) REFERENCES pharma_names(PharmaID) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (CompID) REFERENCES pharma_compounds(CompID) ON UPDATE CASCADE ON DELETE SET NULL,
	FOREIGN KEY (OrderNumber) REFERENCES pharma_orders(OrderNumber) ON UPDATE CASCADE ON DELETE SET NULL
) WITHOUT ROWID;
*/